spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javen_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/javen_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456